(function(){var h={},mt={},c={id:"6bcd52f51e9b3dce32bec4a3997715ac",dm:["csdn.net","dingyue.programmer.com.cn","gitbook.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:true,align:1,nv:1,vdur:1800000,age:31536000000,rec:1,rp:[[119608, 2]],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,aet:'',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var q=void 0,r=!0,t=null,u=!1;mt.cookie={};mt.cookie.set=function(b,a,e){var g;e.Y&&(g=new Date,g.setTime(g.getTime()+e.Y));document.cookie=b+"="+a+(e.domain?"; domain="+e.domain:"")+(e.path?"; path="+e.path:"")+(g?"; expires="+g.toGMTString():"")+(e.Wb?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};mt.lang={};mt.lang.d=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};
mt.lang.ya=function(b){return mt.lang.d(b,"Number")&&isFinite(b)};mt.lang.ea=function(){return mt.lang.d(c.aet,"String")};mt.lang.i=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.G=function(b,a){var e=u;if(b==t||!mt.lang.d(b,"Array")||a===q)return e;if(Array.prototype.indexOf)e=-1!==b.indexOf(a);else for(var g=0;g<b.length;g++)if(b[g]===a){e=r;break}return e};
(function(){var b=mt.lang;mt.e={};mt.e.ta=function(a){return document.getElementById(a)};mt.e.ba=function(a,b){var g=[],k=[];if(!a)return k;for(;a.parentNode!=t;){for(var l=0,n=0,m=a.parentNode.childNodes.length,f=0;f<m;f++){var d=a.parentNode.childNodes[f];if(d.nodeName===a.nodeName&&(l++,d===a&&(n=l),0<n&&1<l))break}if((m=""!==a.id)&&b){g.unshift("#"+encodeURIComponent(a.id));break}else m&&(m="#"+encodeURIComponent(a.id),m=0<g.length?m+">"+g.join(">"):m,k.push(m)),g.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+
(1<l?"["+n+"]":""));a=a.parentNode}k.push(g.join(">"));return k};mt.e.va=function(a){return(a=mt.e.ba(a,r))&&a.length?String(a[0]):""};mt.e.Sb=function(a){return mt.e.ba(a,u)};mt.e.Za=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.e.ab=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.e.gb=function(a){var b={top:0,left:0};if(!a)return b;var g=mt.e.ab(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());
return{top:b.top+(window.pageYOffset||g.scrollTop)-(g.clientTop||0),left:b.left+(window.pageXOffset||g.scrollLeft)-(g.clientLeft||0)}};mt.e.getAttribute=function(a,b){var g=a.getAttribute&&a.getAttribute(b)||t;if(!g&&a.attributes&&a.attributes.length)for(var k=a.attributes,l=k.length,n=0;n<l;n++)k[n].nodeName===b&&(g=k[n].nodeValue);return g};mt.e.M=function(a){var b="document";a.tagName!==q&&(b=a.tagName);return b.toLowerCase()};mt.e.jb=function(a){var e="";a.textContent?e=b.trim(a.textContent):
a.innerText&&(e=b.trim(a.innerText));e&&(e=e.replace(/\s+/g," ").substring(0,255));return e};mt.e.bb=function(a){var b=mt.e.M(a);"input"===b&&("button"===a.type||"submit"===a.type)?a=a.value||"":"img"===b?(b=mt.e.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.e.jb(a);return String(a).substring(0,255)};(function(){(mt.e.Ba=function(){function a(){if(!a.O){a.O=r;for(var b=0,g=k.length;b<g;b++)k[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(g){setTimeout(b,
1);return}a()}var g=u,k=[],l;document.addEventListener?l=function(){document.removeEventListener("DOMContentLoaded",l,u);a()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),a())});(function(){if(!g)if(g=r,"complete"===document.readyState)a.O=r;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",l,u),window.addEventListener("load",a,u);else if(document.attachEvent){document.attachEvent("onreadystatechange",
l);window.attachEvent("onload",a);var k=u;try{k=window.frameElement==t}catch(m){}document.documentElement.doScroll&&k&&b()}})();return function(b){a.O?b():k.push(b)}}()).O=u})();return mt.e})();mt.event={};mt.event.c=function(b,a,e){b.attachEvent?b.attachEvent("on"+a,function(a){e.call(b,a)}):b.addEventListener&&b.addEventListener(a,e,u)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=u};
(function(){var b=mt.event;mt.g={};mt.g.da=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.ub=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:q;mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.Cb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.F=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.A=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.orientation=0;(function(){function a(){var a=0;window.orientation!==q&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==q)&&(a=screen.orientation.angle);mt.g.orientation=a}a();b.c(window,"orientationchange",a)})();return mt.g})();
mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=e[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(g){switch(typeof g){case "undefined":return"undefined";case "number":return isFinite(g)?String(g):"null";case "string":return b(g);case "boolean":return String(g);
default:if(g===t)return"null";if(g instanceof Array){var e=["["],l=g.length,n,m,f;for(m=0;m<l;m++)switch(f=g[m],typeof f){case "undefined":case "function":case "unknown":break;default:n&&e.push(","),e.push(mt.m.stringify(f)),n=1}e.push("]");return e.join("")}if(g instanceof Date)return'"'+g.getFullYear()+"-"+a(g.getMonth()+1)+"-"+a(g.getDate())+"T"+a(g.getHours())+":"+a(g.getMinutes())+":"+a(g.getSeconds())+'"';n=["{"];m=mt.m.stringify;for(l in g)if(Object.prototype.hasOwnProperty.call(g,l))switch(f=
g[l],typeof f){case "undefined":case "unknown":case "function":break;default:e&&n.push(","),e=1,n.push(m(l)+":"+m(f))}n.push("}");return n.join("")}}}();mt.localStorage={};mt.localStorage.T=function(){if(!mt.localStorage.j)try{mt.localStorage.j=document.createElement("input"),mt.localStorage.j.type="hidden",mt.localStorage.j.style.display="none",mt.localStorage.j.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.j)}catch(b){return u}return r};
mt.localStorage.set=function(b,a,e){var g=new Date;g.setTime(g.getTime()+e||31536E6);try{window.localStorage?(a=g.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.T()&&(mt.localStorage.j.expires=g.toUTCString(),mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.setAttribute(b,a),mt.localStorage.j.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),e=b.substring(0,a)-0;if(e&&e>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.T())try{return mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.getAttribute(b)}catch(g){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.T())try{mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.removeAttribute(b),mt.localStorage.j.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(e){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Da={};mt.Da.log=function(b,a){var e=new Image,g="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[g]=e;e.onload=e.onerror=e.onabort=function(){e.onload=e.onerror=e.onabort=t;e=window[g]=t;a&&a(b)};e.src=b};mt.la={};
mt.la.lb=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(e){}return b};
mt.la.Rb=function(b,a,e,g,k){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+e+'" height="'+g+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(k||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+e+'" height="'+g+'" src="'+a+'" flashvars="'+(k||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(b,a){var e=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return e?e[3]:t};mt.url.Tb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.eb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.aa=function(b){return(b=mt.url.eb(b))?b.replace(/:\d+$/,""):b};mt.url.ba=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=u,b=document.getElementsByTagName("script"),g=b.length,g=100<g?100:g,k=0;k<g;k++){var l=b[k].src;if(l&&0===l.indexOf("https://hm.baidu.com/h")){a=r;break}}return a}return h.Ya=b})();var A=h.Ya;
h.l={Ub:"http://tongji.baidu.com/hm-web/welcome/ico",ia:"hm.baidu.com/hm.gif",Ka:"tongji.baidu.com",qb:"hmmd",rb:"hmpl",Nb:"utm_medium",pb:"hmkw",Pb:"utm_term",nb:"hmci",Mb:"utm_content",tb:"hmsr",Ob:"utm_source",ob:"hmcu",Lb:"utm_campaign",B:0,p:Math.round(+new Date/1E3),D:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",P:A()||"https:"===document.location.protocol?"https:":"http:",Vb:0,Qa:6E5,wb:6E5,Db:5E3,Ra:5,C:1024,Pa:1,z:2147483647,Ea:"kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt".split(" "),
H:r,qa:["a","input","button"],Ma:{id:"data-hm-id",W:"data-hm-class",na:"data-hm-xpath",content:"data-hm-content",S:"data-hm-tag",link:"data-hm-link"},pa:"data-hm-enabled",oa:"data-hm-disabled"};(function(){var b={s:{},c:function(a,b){this.s[a]=this.s[a]||[];this.s[a].push(b)},L:function(a,b){this.s[a]=this.s[a]||[];for(var g=this.s[a].length,k=0;k<g;k++)this.s[a][k](b)}};return h.o=b})();
(function(){function b(b,g){var k=document.createElement("script");k.charset="utf-8";a.d(g,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=t,g()}:k.onload=function(){g()});k.src=b;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(k,l)}var a=mt.lang;return h.load=b})();
(function(){function b(){var b="";h.a.b.nv?(b=encodeURIComponent(document.referrer),window.sessionStorage?e.set("Hm_from_"+c.id,b):a.set("Hm_from_"+c.id,b,864E5)):b=(window.sessionStorage?e.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||"";return b}var a=mt.localStorage,e=mt.sessionStorage;return h.sa=b})();
(function(){var b=mt.e,a=mt.lang,e=mt.event,g=mt.g,k=h.l,l=h.o,n=[],m={Fa:function(){c.ctrk&&(e.c(document,"mouseup",m.Oa()),e.c(window,"unload",function(){m.Q()}),setInterval(function(){m.Q()},k.Qa))},Oa:function(){return function(d){d=m.$a(d);if(""!==d){var a=(k.P+"//"+k.ia+"?"+h.a.Ca().replace(/ep=[^&]*/,"ep="+encodeURIComponent(d))).length;a+(k.z+"").length>k.C||(a+encodeURIComponent(n.join("!")+(n.length?"!":"")).length+(k.z+"").length>k.C&&m.Q(),n.push(d),(n.length>=k.Ra||/\*a\*/.test(d))&&
m.Q())}}},$a:function(d){var e=d.target||d.srcElement;if(0===k.Pa){var p=(e.tagName||"").toLowerCase();if("embed"==p||"object"==p)return""}var s;g.da?(s=Math.max(document.documentElement.scrollTop,document.body.scrollTop),p=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),p=d.clientX+p,s=d.clientY+s):(p=d.pageX,s=d.pageY);d=m.fb(d,e,p,s);var f=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:p-=f/2;break;case 2:p-=f}f=
[];f.push(p);f.push(s);f.push(d.xb);f.push(d.yb);f.push(d.Ab);f.push(a.i(d.zb));f.push(d.Qb);f.push(d.mb);(e="a"===(e.tagName||"").toLowerCase()?e:b.Za(e))?(f.push("a"),f.push(a.i(encodeURIComponent(e.href)))):f.push("b");return f.join("*")},fb:function(d,f,p,s){d=b.va(f);var e=0,k=0,l=0,n=0;if(f&&(e=f.offsetWidth||f.clientWidth,k=f.offsetHeight||f.clientHeight,n=b.gb(f),l=n.left,n=n.top,a.d(f.getBBox,"Function")&&(k=f.getBBox(),e=k.width,k=k.height),"html"===(f.tagName||"").toLowerCase()))e=Math.max(e,
f.clientWidth),k=Math.max(k,f.clientHeight);return{xb:Math.round(100*((p-l)/e)),yb:Math.round(100*((s-n)/k)),Ab:g.orientation,zb:d,Qb:e,mb:k}},Q:function(){0!==n.length&&(h.a.b.et=2,h.a.b.ep=n.join("!"),h.a.h(),n=[])}},f={Ia:function(){c.ctrk&&setInterval(f.Eb,k.Db)},Eb:function(){var d=g.F()+g.A();0<d-h.a.b.vl&&(h.a.b.vl=d)}};l.c("pv-b",m.Fa);l.c("pv-b",f.Ia);return m})();
(function(){var b=mt.lang,a=mt.e,e=mt.event,g=mt.g,k=h.l,l=h.o,n=+new Date,m=[],f={ra:function(){return function(d){if(h.a&&h.a.H&&c.aet&&c.aet.length){var e=d.target||d.srcElement;if(e){var p=h.a.qa,s=a.getAttribute(e,k.pa)!=t?r:u;if(a.getAttribute(e,k.oa)==t)if(s)f.U(f.$(e,d));else{var g=a.M(e);if(b.G(p,"*")||b.G(p,g))f.U(f.$(e,d));else for(;e.parentNode!=t;){var s=e.parentNode,g=a.M(s),l="a"===g&&b.G(p,"a")?r:u,g="button"===g&&b.G(p,"button")?r:u,n=a.getAttribute(s,k.pa)!=t?r:u;if(a.getAttribute(s,
k.oa)==t&&(l||g||n)){f.U(f.$(s,d));break}e=e.parentNode}}}}}},$:function(d,e){var p={},f=k.Ma;p.id=a.getAttribute(d,f.id)||a.getAttribute(d,"id")||"";p.W=a.getAttribute(d,f.W)||a.getAttribute(d,"class")||"";p.na=a.getAttribute(d,f.na)||a.va(d);p.content=a.getAttribute(d,f.content)||a.bb(d);p.S=a.getAttribute(d,f.S)||a.M(d);p.link=a.getAttribute(d,f.link)||a.getAttribute(d,"href")||"";p.type=e.type||"click";f=b.ya(d.offsetTop)?d.offsetTop:0;"click"===e.type?f=g.da?e.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):e.pageY:"touchend"===e.type&&(e.ga&&b.d(e.ga.changedTouches,"Array")&&e.ga.changedTouches.length)&&(f=e.ga.changedTouches[0].pageY);p.Kb=f;return p},U:function(d){var a=b.i,a=[+new Date-(h.a.w!==q?h.a.w:n),a(d.id),a(d.W),a(d.S),a(d.na),a(d.link),a(d.content),d.type,d.Kb].join("*");f.V(a);b.G(["a"],d.S)&&b.d(this.J(),"Function")&&this.J()()},V:function(d){d.length>k.C||(encodeURIComponent(m.join("!")+d).length>k.C&&(f.K(m.join("!")),m=[]),m.push(d))},K:function(d){h.a.b.et=
5;h.a.b.ep=d;h.a.h()},J:function(){return function(){m&&m.length&&(f.K(m.join("!")),m=[])}}};b.ea()&&""!==c.aet&&l.c("pv-b",function(){e.c(document,"click",f.ra());"ontouchend"in document&&e.c(window,"touchend",f.ra());e.c(window,"unload",f.J())});return f})();
(function(){var b=mt.event,a=mt.g,e=h.l,g=h.o,k=+new Date,l=[],n=t,m={Ua:function(){return function(){h.a&&(h.a.H&&c.aet&&c.aet.length)&&(window.clearTimeout(n),n=window.setTimeout(function(){m.Ha(a.F()+a.A())},150))}},Ha:function(a){m.V([+new Date-(h.a.w!==q?h.a.w:k),a].join("*"))},V:function(a){if(encodeURIComponent(l.join("!")+a).length>e.C||5<l.length)m.K(l.join("!")),l=[];l.push(a)},K:function(b){h.a.b.et=6;h.a.b.vh=a.A();h.a.b.ep=b;h.a.h()},J:function(){return function(){l&&l.length&&(m.K(l.join("!")),
l=[])}}};mt.lang.ea()&&""!==c.aet&&g.c("pv-b",function(){b.c(window,"scroll",m.Ua());b.c(window,"unload",m.J())});return m})();
(function(){var b=mt.e,a=h.l,e=h.load,g=h.sa;h.o.c("pv-b",function(){var k=a.protocol+"//crs.baidu.com/";c.rec&&b.Ba(function(){for(var l=0,n=c.rp.length;l<n;l++){var m=c.rp[l][0],f=c.rp[l][1],d=b.ta("hm_t_"+m);if(f&&!(2==f&&!d||d&&""!==d.innerHTML))d="",d=Math.round(Math.random()*a.z),d=4==f?k+"hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+d].join("&"):k+"t.js?"+["siteId="+c.id,"planId="+m,"from="+g(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
d].join("&"),e(d)}})})})();(function(){var b=h.l,a=h.load,e=h.sa;h.o.c("pv-b",function(){if(c.trust&&c.vcard){var g="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+e(),"rnd="+Math.round(Math.random()*b.z),"hm=1"].join("&");a(g)}})})();
(function(){function b(){return function(){h.a.b.nv=0;h.a.b.st=4;h.a.b.et=3;h.a.b.ep=h.X.hb()+","+h.X.cb();h.a.h()}}function a(){clearTimeout(z);var b;x&&(b="visible"==document[x]);y&&(b=!document[y]);m="undefined"==typeof b?r:b;if((!n||!f)&&m&&d)w=r,p=+new Date;else if(n&&f&&(!m||!d))w=u,s+=+new Date-p;n=m;f=d;z=setTimeout(a,100)}function e(d){var a=document,b="";if(d in a)b=d;else for(var p=["webkit","ms","moz","o"],e=0;e<p.length;e++){var f=p[e]+d.charAt(0).toUpperCase()+d.slice(1);if(f in a){b=
f;break}}return b}function g(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))d="focus"==b.type||"focusin"==b.type?r:u,a()}var k=mt.event,l=h.o,n=r,m=r,f=r,d=r,v=+new Date,p=v,s=0,w=r,x=e("visibilityState"),y=e("hidden"),z;a();(function(){var d=x.replace(/[vV]isibilityState/,"visibilitychange");k.c(document,d,a);k.c(window,"pageshow",a);k.c(window,"pagehide",a);"object"==typeof document.onfocusin?(k.c(document,"focusin",g),k.c(document,"focusout",g)):(k.c(window,"focus",g),
k.c(window,"blur",g))})();h.X={hb:function(){return+new Date-v},cb:function(){return w?+new Date-p+s:s}};l.c("pv-b",function(){k.c(window,"unload",b())});return h.X})();
(function(){var b=mt.lang,a=h.l,e=h.load,g={vb:function(g){if((window._dxt===q||b.d(window._dxt,"Array"))&&"undefined"!==typeof h.a){var l=h.a.Z();e([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),g)}},Jb:function(a){if(b.d(a,"String")||b.d(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Sa=g})();
(function(){function b(d,a,b,e){if(!(d===q||a===q||e===q)){if(""===d)return[a,b,e].join("*");d=String(d).split("!");for(var f,g=u,k=0;k<d.length;k++)if(f=d[k].split("*"),String(a)===f[0]){f[1]=b;f[2]=e;d[k]=f.join("*");g=r;break}g||d.push([a,b,e].join("*"));return d.join("!")}}function a(d){for(var b in d)if({}.hasOwnProperty.call(d,b)){var p=d[b];e.d(p,"Object")||e.d(p,"Array")?a(p):d[b]=String(p)}}var e=mt.lang,g=mt.m,k=mt.g,l=h.l,n=h.o,m=h.Sa,f={I:[],R:0,za:u,r:{ma:"",page:""},init:function(){f.f=
0;n.c("pv-b",function(){f.Ta();f.Wa()});n.c("pv-d",function(){f.Xa();f.r.page=""});n.c("stag-b",function(){h.a.b.api=f.f||f.R?f.f+"_"+f.R:"";h.a.b.ct=[decodeURIComponent(h.a.getData("Hm_ct_"+c.id)||""),f.r.ma,f.r.page].join("!")});n.c("stag-d",function(){h.a.b.api=0;f.f=0;f.R=0})},Ta:function(){var d=window._hmt||[];if(!d||e.d(d,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var d=window._hmt,a=0;a<arguments.length;a++){var b=arguments[a];e.d(b,"Array")&&(d.cmd[d.id].push(b),"_setAccount"===
b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],d.id=b,d.cmd[b]=d.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,d)},Wa:function(){var d=window._hmt;if(d&&d.cmd&&d.cmd[c.id])for(var a=d.cmd[c.id],b=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,g=a.length;e<g;e++){var k=a[e];b.test(k[0])?f.I.push(k):f.ha(k)}d.cmd[c.id]={push:f.ha}},Xa:function(){if(0<f.I.length)for(var d=0,a=f.I.length;d<a;d++)f.ha(f.I[d]);f.I=t},ha:function(d){var a=d[0];if(f.hasOwnProperty(a)&&
e.d(f[a],"Function"))f[a](d)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(f.f|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],u===a||r===a))f.f|=2,h.a.wa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){f.f|=4;h.a.b.et=0;h.a.b.ep="";h.a.b.vl=k.F()+k.A();h.a.b.kb=0;h.a.ca?(h.a.b.nv=0,h.a.b.st=4):h.a.ca=r;var b=h.a.b.u,p=h.a.b.su;h.a.b.u=l.protocol+"//"+document.location.host+a[1];f.za||(h.a.b.su=document.location.href);h.a.h();h.a.b.u=b;
h.a.b.su=p;h.a.w=+new Date}},_trackEvent:function(a){2<a.length&&(f.f|=8,h.a.b.nv=0,h.a.b.st=4,h.a.b.et=4,h.a.b.ep=e.i(a[1])+"*"+e.i(a[2])+(a[3]?"*"+e.i(a[3]):"")+(a[4]?"*"+e.i(a[4]):""),h.a.h())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],p=a[4]||3;if(0<b&&6>b&&0<p&&4>p){f.R++;for(var g=(h.a.b.cv||"*").split("!"),k=g.length;k<b-1;k++)g.push("*");g[b-1]=p+"*"+e.i(a[2])+"*"+e.i(a[3]);h.a.b.cv=g.join("!");a=h.a.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.a.setData("Hm_cv_"+
c.id,encodeURIComponent(a),c.age):h.a.Bb("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var f=e.i(a[1]);a=e.i(a[2]);if(f!==q&&a!==q){var p=decodeURIComponent(h.a.getData("Hm_ct_"+c.id)||""),p=b(p,f,1,a);h.a.setData("Hm_ct_"+c.id,encodeURIComponent(p),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var g=e.i(a[1]);a=e.i(a[2]);if(g!==q&&a!==q){var p=f.r.ma,p=b(p,g,2,a);f.r.ma=p}}},_setPageTag:function(a){if(!(3>a.length)){var g=e.i(a[1]);a=e.i(a[2]);if(g!==q&&a!==q){var p=f.r.page,
p=b(p,g,3,a);f.r.page=p}}},_setReferrerOverride:function(a){1<a.length&&(h.a.b.su=a[1].charAt&&"/"===a[1].charAt(0)?l.protocol+"//"+window.location.host+a[1]:a[1],f.za=r)},_trackOrder:function(b){b=b[1];e.d(b,"Object")&&(a(b),f.f|=16,h.a.b.nv=0,h.a.b.st=4,h.a.b.et=94,h.a.b.ep=g.stringify(b),h.a.h())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])f.f|=32,h.a.b.et=93,h.a.b.ep=a,h.a.h()},_trackRTPageview:function(b){b=b[1];e.d(b,"Object")&&(a(b),b=g.stringify(b),
512>=encodeURIComponent(b).length&&(f.f|=64,h.a.b.rt=b))},_trackRTEvent:function(b){b=b[1];if(e.d(b,"Object")){a(b);b=encodeURIComponent(g.stringify(b));var k=function(a){var b=h.a.b.rt;f.f|=128;h.a.b.et=90;h.a.b.rt=a;h.a.h();h.a.b.rt=b},p=b.length;if(900>=p)k.call(this,b);else for(var p=Math.ceil(p/900),s="block|"+Math.round(Math.random()*l.z).toString(16)+"|"+p+"|",n=[],m=0;m<p;m++)n.push(m),n.push(b.substring(900*m,900*m+900)),k.call(this,s+n.join("|")),n=[]}},_setUserId:function(a){a=a[1];m.vb();
m.Jb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],u===a||r===a))h.a.xa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],u===a||r===a))h.a.H=a}};f.init();h.La=f;return h.La})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=r,this.b={},this.xa=this.wa=r,this.H=d.H,this.qa=k.ea()&&0<c.aet.length?c.aet.split(","):"",this.ca=u,this.init())}var a=mt.url,e=mt.Da,g=mt.la,k=mt.lang,l=mt.cookie,n=mt.g,m=mt.localStorage,f=mt.sessionStorage,d=h.l,v=h.o;b.prototype={fa:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},Aa:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},N:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.Aa(b,c.dm[d]))return r}else{var e=a.aa(b);if(e&&this.fa(e,c.dm[d]))return r}return u},Z:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.fa(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},ua:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.Aa(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,
"$1")+"/"}return"/"},ib:function(){if(!document.referrer)return d.p-d.B>c.vdur?1:4;var b=u;this.N(document.referrer)&&this.N(document.location.href)?b=r:(b=a.aa(document.referrer),b=this.fa(b||"",document.location.hostname));return b?d.p-d.B>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||f.get(a)||m.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.Z(),path:this.ua(),Y:d}),d?m.set(a,b,d):f.set(a,b)}catch(e){}},Bb:function(a){try{l.set(a,"",{domain:this.Z(),path:this.ua(),
Y:-1}),f.remove(a),m.remove(a)}catch(b){}},Hb:function(){var a,b,e,f,g;d.B=this.getData("Hm_lpvt_"+c.id)||0;13===d.B.length&&(d.B=Math.round(d.B/1E3));b=this.ib();a=4!==b?1:0;if(e=this.getData("Hm_lvt_"+c.id)){f=e.split(",");for(g=f.length-1;0<=g;g--)13===f[g].length&&(f[g]=""+Math.round(f[g]/1E3));for(;2592E3<d.p-f[0];)f.shift();g=4>f.length?2:3;for(1===a&&f.push(d.p);4<f.length;)f.shift();e=f.join(",");f=f[f.length-1]}else e=d.p,f="",g=1;this.setData("Hm_lvt_"+c.id,e,c.age);this.setData("Hm_lpvt_"+
c.id,d.p);e=d.p===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.N(document.location.href)&&(""===document.referrer||this.N(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=e;this.b.lt=f;this.b.lv=g},Ca:function(){for(var a=[],b=this.b.et,e=+new Date,f=0,g=d.Ea.length;f<g;f++){var k=d.Ea[f],l=this.b[k];"undefined"!==typeof l&&""!==l&&("tt"!==k||"tt"===k&&0===b)&&(("ct"!==k||"ct"===k&&0===b)&&("kb"!==k||"kb"===k&&3===b))&&a.push(k+"="+encodeURIComponent(l))}switch(b){case 0:a.push("sn="+
d.D);this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 3:a.push("sn="+d.D);break;case 5:a.push("sn="+d.D);a.push("_lpt="+this.w);a.push("_ct="+e);break;case 6:a.push("sn="+d.D);a.push("_lpt="+this.w);a.push("_ct="+e);break;case 85:a.push("sn="+d.D);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},Ib:function(){this.Hb();this.b.si=c.id;this.b.su=document.referrer;this.b.ds=n.Cb;this.b.cl=n.colorDepth+"-bit";this.b.ln=String(n.language).toLowerCase();this.b.ja=n.javaEnabled?
1:0;this.b.ck=n.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=g.lb();this.b.v="1.2.38";this.b.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=n.F()+n.A();var b=document.location.href;this.b.cm=a.k(b,d.qb)||"";this.b.cp=a.k(b,d.rb)||a.k(b,d.Nb)||"";this.b.cw=a.k(b,d.pb)||a.k(b,d.Pb)||"";this.b.ci=a.k(b,d.nb)||a.k(b,d.Mb)||"";this.b.cf=a.k(b,d.tb)||a.k(b,d.Ob)||"";this.b.cu=a.k(b,d.ob)||a.k(b,d.Lb)||""},init:function(){try{this.Ib(),
0===this.b.nv?this.Gb():this.ka(".*"),h.a=this,this.Na(),v.L("pv-b"),this.Fb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));e.log(d.P+"//"+d.ia+"?"+b.join("&"))}},Fb:function(){function a(){v.L("pv-d")}this.wa?(this.ca=r,this.b.et=0,this.b.ep="",this.b.vl=n.F()+n.A(),this.h(a)):a();this.w=+new Date},h:function(a){if(this.xa){var b=this;b.b.rnd=Math.round(Math.random()*d.z);
v.L("stag-b");var f=d.P+"//"+d.ia+"?"+b.Ca();v.L("stag-d");b.Ja(f);e.log(f,function(d){b.ka(d);k.d(a,"Function")&&a.call(b)})}},Na:function(){var b=document.location.hash.substring(1),e=RegExp(c.id),f=a.aa(document.referrer)===d.Ka?1:0,g=a.k(b,"jn"),k=/^heatlink$|^select$|^pageclick$/.test(g);b&&(e.test(b)&&f&&k)&&(this.b.rnd=Math.round(Math.random()*d.z),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",d.protocol+"//"+
c.js+g+".js?"+this.b.rnd),g=document.getElementsByTagName("script")[0],g.parentNode.insertBefore(b,g))},Ja:function(a){var b=f.get("Hm_unsent_"+c.id)||"",d=this.b.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");f.set("Hm_unsent_"+c.id,b)},ka:function(a){var b=f.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,
""))?f.set("Hm_unsent_"+c.id,b):f.remove("Hm_unsent_"+c.id))},Gb:function(){var a=this,b=f.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),g=function(b){e.log(d.P+"//"+decodeURIComponent(b),function(b){a.ka(b)})},k=0,l=b.length;k<l;k++)g(b[k])}};return new b})();
(function(){var b=mt.event,a=mt.lang,e=h.l;if(c.kbtrk&&"undefined"!==typeof h.a){h.a.b.kb=a.ya(h.a.b.kb)?h.a.b.kb:0;var g=function(){h.a.b.et=85;h.a.b.ep=h.a.b.kb;h.a.h()};b.c(document,"keyup",function(){h.a.b.kb++});b.c(window,"unload",function(){g()});setInterval(g,e.wb)}})();var B=h.l,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.event,a=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.a){var e=function(a){var b=performance.timing,e=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:e,end:a,value:0<a-e?a-e:0}},g=function(){var b;b=e("navigation");var g=e("request");b={netAll:g.start-b.start,netDns:e("domainLookup").value,netTcp:e("connect").value,srv:e("response").start-g.start,dom:performance.timing.domInteractive-performance.timing.fetchStart,loadEvent:e("loadEvent").end-
b.start};h.a.b.et=87;h.a.b.ep=a.stringify(b);h.a.h()};b.c(window,"load",function(){setTimeout(g,500)})}}catch(k){}})();
(function(){var b=mt.g,a=mt.lang,e=mt.event,g=mt.m;if("undefined"!==typeof h.a&&(c.med||(!b.da||7<b.ub)&&c.cvcc)){var k,l,n,m,f=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},d=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===u)return u},v=function(b,d){var e={};e.n=k;e.t="clk";e.v=b;if(d){var f=d.getAttribute("href"),l=d.getAttribute("onclick")?""+d.getAttribute("onclick"):t,m=d.getAttribute("id")||"";n.test(f)?(e.sn="mediate",
e.snv=f):a.d(l,"String")&&n.test(l)&&(e.sn="wrap",e.snv=l);e.id=m}h.a.b.et=86;h.a.b.ep=g.stringify(e);h.a.h();for(e=+new Date;400>=+new Date-e;);};if(c.med)l="/zoosnet",k="swt",n=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=f(document.getElementsByTagName("a")),b=[].concat.apply(b,f(document.getElementsByTagName("area"))),b=[].concat.apply(b,f(document.getElementsByTagName("img"))),d,e,g=0,k=b.length;g<k;g++)d=b[g],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(n.test(e)||n.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){l="/other-comm";k="other";n=c.cvcc.q||q;var p=c.cvcc.id||q;m={click:function(){for(var a=[],b=f(document.getElementsByTagName("a")),b=[].concat.apply(b,f(document.getElementsByTagName("area"))),b=[].concat.apply(b,f(document.getElementsByTagName("img"))),d,e,g,k=0,l=b.length;k<l;k++)d=b[k],n!==q?(e=d.getAttribute("onclick"),g=d.getAttribute("href"),p?(d=d.getAttribute("id"),(n.test(e)||n.test(g)||p.test(d))&&
a.push(b[k])):(n.test(e)||n.test(g))&&a.push(b[k])):p!==q&&(d=d.getAttribute("id"),p.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof n){var s;l+=/\/$/.test(l)?"":"/";var w=function(b,d){if(s===d)return v(l+b,d),u;if(a.d(d,"Array")||a.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(s===d[e])return v(l+b+"/"+(e+1),d[e]),u};e.c(document,"mousedown",function(b){b=b||window.event;s=b.target||b.srcElement;var e={};for(d(m,function(b,d){e[b]=a.d(d,"Function")?d():document.getElementById(d)});s&&
s!==document&&d(e,w)!==u;)s=s.parentNode})}}})();(function(){var b=mt.e,a=mt.lang,e=mt.event,g=mt.m;if("undefined"!==typeof h.a&&a.d(c.cvcf,"Array")&&0<c.cvcf.length){var k={Ga:function(){for(var a=c.cvcf.length,g,m=0;m<a;m++)(g=b.ta(decodeURIComponent(c.cvcf[m])))&&e.c(g,"click",k.Va())},Va:function(){return function(){h.a.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.a.b.ep=g.stringify(a);h.a.h()}}};b.Ba(function(){k.Ga()})}})();
(function(){var b=mt.event,a=mt.m;if(c.med&&"undefined"!==typeof h.a){var e=+new Date,g={n:"anti",sb:0,kb:0,clk:0},k=function(){h.a.b.et=86;h.a.b.ep=a.stringify(g);h.a.h()};b.c(document,"click",function(){g.clk++});b.c(document,"keyup",function(){g.kb=1});b.c(window,"scroll",function(){g.sb++});b.c(window,"unload",function(){g.t=+new Date-e;k()});b.c(window,"load",function(){setTimeout(k,5E3)})}})();})();
